### ISSUE TITLE
Load from memory

### ISSUE THREAD

**Issue by ahoarau** [guybrush77/rapidobj#2]
Hello, This library seems very nice.
Would it be possible to add the ability to open files from `std::istream` ?
Thanks !

**Comment by guybrush77** [comment]
Hello Antoine,

I apologise for the very late reply. I was busy lately and forgot about my hobby project.

The principal design goal for rapidobj is to provide fast parsing. The way it works is, a file in divided into chunks parsed in parallel and asynchronously loaded using low-level OS functions. Not that I am an expert on C++ streams, but the word is that they are slow and inflexible; I am concerned this interface would violate the performance goal.

However, if all you need it to load a file from memory, perhaps a simpler interface (e.g. std::string_view) would work fine?

Could you tell me about your use case, so I can understand the issue you are trying to solve better?

Cheers,
Slobo

**Comment by guybrush77** [comment]
If another system loads an .obj file and passes you a std::istream, what if that .obj contained a reference to a material library file (mtllib)? How is this handled? Or maybe it is not a concern in your use case?

**Comment by ahoarau** [comment]
Definitely not a concern here.

**Comment by ahoarau** [comment]
Hello ! I'm ready to test the branch, could you rebase it ? Thanks a bunch !

**Comment by guybrush77** [comment]
These are actually two different requests.

@ahoarau wants to load the file from `std::istream`. This is going to be much slower for large files because reading from a sequential source precludes parsing parallelization.

@K3rn1n4tor would like to load from memory. The API could look like `rapidobj::ParseStream(std::string_view)` or something to that effect. In this case, parallelization is possible but it still won't be quite as fast as the regular ParseStream call. rapidobj is optimized for parsing large files stored on block devices.

I will implement `rapidobj::ParseStream(std::string_view)` first, because @ahoarau was first to make the API request. The ParseStream branch already exists, but it has diverged from the main branch. It might take me a few days for merging. Please stay tuned.

**Comment by ahoarau** [comment]
@guybrush77 no worries on being much slower for istreams, as soon as it's still fast on file loading that's fine - as a user point of view.

**Comment by guybrush77** [comment]
@ahoarau I have added `ParseStream()` function. Could you try the latest master? Let me know if it works for you.

**Comment by guybrush77** [comment]
@K3rn1n4tor Is `ParseStream()` sufficient for your purposes? If the files you are loading from memory aren't too large, you should be able to use istrstream. But if they are large, I could implement `ParseString()` or something similar.

**Comment by K3rn1n4tor** [comment]
I'm currently working on other items but will test this within the next two weeks. Maybe it's enough to have this. I'll let you know. Otherwise, we need something to operate on char or byte arrays. :)

**Comment by guybrush77** [comment]
The new API is implemented, tested and released (v1.1).
